version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "elasticbeanstalk-us-east-2-466503166845"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run prestart:prod
    post_build:
         commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'